### ISSUE TITLE
Information on each day of the cycle

### ISSUE THREAD

**Issue by DanMorriss** [alcl2000/womenswellnesswarriors#26]

**Comment by missdays** [comment]
## Menstrual Phase
During this phase, you may experience bleeding and discomfort. It's essential to prioritise self-care and manage any discomfort with pain relief.

### Useful Advice
- Stay hydrated.
- Get plenty of rest.
- Use heating pads for comfort.
- Practice gentle exercise like walking or yoga.

### Expected Symptoms
- Menstrual cramps
- Fatigue
- Mood swings

### Useful Articles
- [Tips for Managing Menstrual Cramps](https://www.healthline.com/health/womens-health/how-to-stop-menstrual-cramps)
- [Self-Care During Your Period](https://www.everydayhealth.com/wellness/self-care-during-your-period/)

## Follicular Phase
This phase starts after your period ends and lasts until ovulation. You may feel more energetic and experience a rise in libido.

### Useful Advice
- Focus on nutrient-rich foods.
- Engage in moderate-intensity exercises.
- Prioritise adequate sleep.
- Consider tracking your fertility if trying to conceive.

### Expected Symptoms
- Increased energy levels
- Heightened libido
- Lighter vaginal discharge

### Useful Articles
- [Fertility Tracking Methods](https://www.plannedparenthood.org/learn/birth-control/fertility-awareness)
- [Diet and Exercise for a Healthy Menstrual Cycle](https://www.medicalnewstoday.com/articles/menstrual-cycle-diet)

## Ovulation Phase
This phase typically occurs around mid-cycle and marks the release of an egg from the ovary. You may experience heightened fertility during this time.

### Useful Advice
- Consider using protection if not trying to conceive.
- Monitor ovulation signs like changes in cervical mucus.
- Engage in intimacy if trying to conceive.
- Stay relaxed and stress-free.

### Expected Symptoms
- Increased libido
- Changes in cervical mucus consistency
- Mild pelvic discomfort

### Useful Articles
- [Understanding Ovulation Signs](https://www.healthline.com/health/pregnancy/what-are-the-signs-of-ovulation)
- [Optimising Fertility](https://www.mayoclinic.org/healthy-lifestyle/getting-pregnant/in-depth/fertility/art-20047584)

## Luteal Phase
This phase occurs after ovulation and lasts until the start of your next period. You may experience PMS symptoms during this time.

### Useful Advice
- Practice stress-relief techniques.
- Maintain a balanced diet.
- Stay hydrated.
- Monitor mood changes and seek support if needed.

### Expected Symptoms
- Breast tenderness
- Mood swings
- Bloating

### Useful Articles
- [Managing PMS Symptoms](https://www.webmd.com/women/pms/features/11-ways-to-ease-pms#1)
- [Balanced Diet for Hormonal Balance](https://www.health.harvard.edu/womens-health/a-natural-approach-to-menopause)


Feel free to modify this template as needed!
